"""Fix learning_progress table

Revision ID: 927b7b4bc7bf
Revises: e8d86206ae53
Create Date: 2025-02-20 01:52:33.055999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927b7b4bc7bf'
down_revision: Union[str, None] = 'e8d86206ae53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
