"""Make user.password nullable for OAuth users

Revision ID: b48bccd81211
Revises: e906cf4b3d69
Create Date: 2025-01-31 15:39:13.237607

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b48bccd81211"
down_revision: Union[str, None] = "e906cf4b3d69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "password", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
