"""Add refresh_token column to users

Revision ID: c3630e9eb4e0
Revises: 650063450aeb
Create Date: 2025-01-28 00:09:41.163036

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3630e9eb4e0"
down_revision: Union[str, None] = "650063450aeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quizzes",
        "total_problems_count",
        existing_type=mysql.ENUM("5", "10", "20", "30"),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.add_column(
        "users", sa.Column("refresh_token", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "refresh_token")
    op.alter_column(
        "quizzes",
        "total_problems_count",
        existing_type=sa.Integer(),
        type_=mysql.ENUM("5", "10", "20", "30"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
