"""add_google_oauth

Revision ID: e906cf4b3d69
Revises: 59568056aed8
Create Date: 2025-01-31 15:30:14.711404

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e906cf4b3d69"
down_revision: Union[str, None] = "59568056aed8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users", sa.Column("google_id", mysql.VARCHAR(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "auth_provider",
            mysql.VARCHAR(length=50),
            server_default=sa.text("'local'"),
            nullable=False,
        ),
    )
    op.create_index("google_id", "users", ["google_id"], unique=True)
    op.alter_column(
        "users", "password", existing_type=mysql.VARCHAR(length=255), nullable=True
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("google_id", mysql.VARCHAR(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "auth_provider",
            mysql.VARCHAR(length=50),
            server_default=sa.text("'local'"),
            nullable=False,
        ),
    )
    op.create_index("google_id", "users", ["google_id"], unique=True)
    op.alter_column(
        "users", "password", existing_type=mysql.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
