name: Deploy to AWS EC2

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} /bin/bash << 'EOF'
          cd ~/ticha-BE
          git reset --hard
          git pull origin $(git rev-parse --abbrev-ref HEAD)

          # ✅ PATH 환경 변수 수동 설정 (필수)
          export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

          # ✅ Poetry 가상환경 활성화
          export PATH="$HOME/.local/bin:$PATH"
          export POETRY_HOME="$HOME/.poetry"
          export VIRTUAL_ENV="\$(poetry env info --path)"
          export PATH="\$VIRTUAL_ENV/bin:\$PATH"

          # ✅ Poetry 가상환경 적용 (확실하게)
          source "\$VIRTUAL_ENV/bin/activate"

          # ✅ 명령어 확인 (디버깅용)
          echo "Checking commands..."
          which cat
          which pkill
          which sleep
          which ps
          which grep

          # ✅ EC2에 .env 파일 생성 (GitHub Secrets에서 값 가져오기)
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" > .env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> .env
          echo "MYSQL_HOST=db" >> .env  # 배포 환경에서는 MySQL 컨테이너 사용

          # ✅ 카카오 OAuth 설정
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env
          echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env

          # ✅ 구글 OAuth 설정
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env

          # ✅ JWT 설정
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> .env

          # ✅ 환경설정
          echo "ENV=production" >> .env  # 배포 환경에서는 production

          # ✅ 변경된 .env 파일 확인
          cat .env

          # ✅ 실행 중인 FastAPI 서버 종료
          pkill -f "uvicorn" || true  # 기존 uvicorn 프로세스 종료

          # ✅ FastAPI 서버 실행 (Poetry 환경 적용)
          nohup poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 > fastapi.log 2>&1 &

          # ✅ 실행 상태 확인
          sleep 5
          ps aux | grep uvicorn
          EOF